### ISSUE TITLE
Failure to bind on port 22 on remote VPS - already using for ssh access

### ISSUE THREAD

**Issue by blackdoginet** [shasoco/shasoco#29]
Brilliant idea but does not seem to work on a remote VPS which I usually access through ssh port 22.
Everything works fine until I try to activate when I get the error that docker cannot bind to port 22 because it is already in use

> ERROR: Failed to start the metaproxy: Error: HTTP code is 500 which indicates error: server error - failed to create endpoint shasoco_cloudblackdoginternet on network bridge: Error starting userland proxy: listen tcp 0.0.0.0:22: bind: address already in use

I edited the compose .yml file to try and eliminate binds to host port 22. When I tried to activate again I got blocked from accessing VPS via SHH, so obviously screwed up the edit.

Could you tell me (perhaps post an example) which are the correct edits to make in this file to prevent this happening again?

Thanks in advance
Dave

**Comment by j3k0** [comment]
Hi, we're in the same situation so be sure it's indeed possible.

You can get help by doing

```
$ shasoco create --help

  Usage: shasoco-create [options] <deploy-id> <domain>

  Options:

    -h, --help                        output usage information
    -p, --http-port [PORT]            Port to expose for http (default=80)
    -P, --https-port [PORT]           Port to expose for https (default=443)
    -S, --sslcert [CERT]              SSL Certificate for HTTPS
    -c, --sslcert-self-signed [BOOL]  Is SSL Certificate self-signed (default=true)
    -s, --git-ssh-port [PORT]         Port to expose for git+ssh (default=22)
```

What you are looking for is the `--git-ssh-port [PORT]` option.

If you have a deployment running and being used already, you can also do it "manually" 

`1`. `shasoco stop` it
`2`. edit the `/var/lib/shasoco/deploys/XXX/config.yml` file. Make sure you see:

``` yml
gitSshPort: '2345'
```

`3`. `shasoco up XXX` and `shasoco activate` (if needed)

**Comment by blackdoginet** [comment]
Many thanks that sorted it
