### ISSUE TITLE
Add command: backup/restore

### ISSUE THREAD

**Issue by j3k0** [shasoco/shasoco#7]
`shasoco backup`
1. prepare storage space
2. add metadata (version used to generate backup, project config files)
3. call each service's backup method (who write stuff in their own subfolders)
4. create a backup file from storage space

@flboudet is storage space an issue? How much data are we talking about? (I think mainly of `vault` file server)

To consider: backup storage space being version-controlled.

**Comment by flboudet** [comment]
@j3k0: vault will contain large files (>1GB), it will be probably wise to be able to opt-out the files stored in `vault` from the backups...
